name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build-dotnet:
    name: Build .NET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build --configuration Release
        
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build 
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./Docker/Production/Dockerfile
          build-args: |
            VERSION=0.0.0
          platforms: linux/amd64,linux/arm64
