name: Release

env:
  PRERELEASE_BRANCHES: ''
  
on:
  pull_request:
    types: [ closed ]

jobs:
  release-docker:
    name: Release Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Establish context
        id: context
        uses: dolittle/establish-context-action@v2
        with:
          prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}
      - name: Increment version
        id: increment-version
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/increment-version-action@v2
        with:
          version: ${{ steps.context.outputs.current-version }}
          release-type: ${{ steps.context.outputs.release-type }}
      - name: Prepend to Changelog
        if: ${{ steps.context.outputs.should-publish == 'true' && steps.context.outputs.release-type != 'prerelease' }}
        uses: dolittle/add-to-changelog-action@v2
        with:
          version: ${{ steps.increment-version.outputs.next-version }}
          body: ${{ steps.context.outputs.pr-body }}
          pr-url: ${{ steps.context.outputs.pr-url }}
          changelog-path: CHANGELOG.md
          user-email: build@dolittle.com
          user-name: dolittle-build
      - name: Create GitHub Release
        id: create-release
        uses: dolittle/github-release-action@v2
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        with:
          token: ${{ secrets.BUILD_PAT }}
          version: ${{ steps.increment-version.outputs.next-version }}
          body: ${{ steps.context.outputs.pr-body }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Versioned Tag to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          build-args: |
            VERSION=${{ needs.setup.outputs.next-version }}
          platforms: linux/amd64,linux/arm64
          tags: dolittle/logfeeder:${{ needs.setup.outputs.next-version }}
      - name: Push Latest Tag to Docker Hub
        uses: docker/build-push-action@v2
        if: ${{ needs.setup.outputs.release-type != 'prerelease' }}
        with:
          push: true
          context: .
          build-args: |
            VERSION=${{ needs.setup.outputs.next-version }}
          platforms: linux/amd64,linux/arm64
          tags: dolittle/logfeeder:latest